### ISSUE TITLE
Issues with old sidebar

### ISSUE THREAD

**Issue by kiwichick888** [Lexikos/AutoHotkey_L-Docs#720] opened 2024-11-24 01:46 UTC
Since AutoHotkey changed the style of the Help file, Favourites aren't available anymore so I use compile_chm.ahk to create a Help file with the old sidebar. However, the compiled files have a couple of issues. This has always happened (even back when I was using AHK v1), it isn't a recent occurrence. 

1. Sometimes the Help file crashes when I start typing in the Index field.
2. Script links don't work. When I click a link I receive an error as per the screenshot.

<img width="332" alt="AutoHotkey error" src="https://github.com/user-attachments/assets/cb352268-a5cc-45b9-a1d0-7de2a187522e">

**Comment by Ragnar-F** [comment] 2024-11-24 08:43
Which version of Windows do you use? Which version of Internet Explorer do you have installed?

Issue 1: I cannot reproduce this. If possible, you need to explain step by step how this crash occurs.

Issue 2: I will fix this script error. However, when I close the error dialog, no matter what button I click, the links work as they should. A file download dialog is displayed.

**Comment by kiwichick888** [comment] 2024-11-26 07:35
> Which version of Windows do you use? Which version of Internet Explorer do you have installed?

Windows 10 Pro. As far as I'm aware, Internet Explorer doesn't exist anymore so why would I have it installed? 

> Issue 1: I cannot reproduce this. If possible, you need to explain step by step how this crash occurs.

Not sure how I can explain much more than that. Sometimes when I start typing in the Index field, the help file crashes. Go to the Index tab, start typing, help file closes.

> Issue 2: I will fix this script error. However, when I close the error dialog, no matter what button I click, the links work as they should. A file download dialog is displayed.

Ah, yes, you are correct. The link does work after closing the dialog and re-clicking the link. But it sure would be great to have it fixed 😁👍

**Comment by Ragnar-F** [comment] 2024-11-26 10:10
> Windows 10 Pro. As far as I'm aware, Internet Explorer doesn't exist anymore so why would I have it installed?

This question is only relevant if you are using an older version of Windows. Internet Explorer no longer exists as a standalone application, but can still be used via COM (which is probably also used by Microsoft's ancient CHM viewer). I know from your Windows version that IE11 is automatically used for the docs.
> Not sure how I can explain much more than that. Sometimes when I start typing in the Index field, the help file crashes. Go to the Index tab, start typing, help file closes.

Then the cause is more likely Microsoft's CHM viewer itself, which is probably not fixable from our side. See [Index search in CHM help crashes viewer](https://github.com/python/cpython/issues/79409) for possible solutions. Please let us know if you were able to solve it.

> Ah, yes, you are correct. The link does work after closing the dialog and re-clicking the link. But it sure would be great to have it fixed 😁👍

Fixed via 408347185787520b7bf4f2d030f596e5914c509a.

**Comment by kiwichick888** [comment] 2024-11-26 22:25
> See [Index search in CHM help crashes viewer](https://github.com/python/cpython/issues/79409) for possible solutions. Please let us know if you were able to solve it.

"Typing into the index keyword field frequently crashes the CHM viewer with the first or second character." Thanks, that is exactly the problem I'm having. The only problem is that that link is talking about a Python chm file and I don't know how to relate/apply any of the potential fixes to the AutoHotkey chm.

> Fixed via [4083471](https://github.com/AutoHotkey/AutoHotkeyDocs/commit/408347185787520b7bf4f2d030f596e5914c509a).

Thanks again, I can confirm it's fixed.

**Closed as completed** 2024-12-03 20:44 UTC
